lib/werkzeug/urls.py
# -*- coding: utf-8 -*-
"""
    werkzeug.urls
    ~~~~~~~~~~~~~

    This module implements various URL related functions.

    :copyright: (c) 2013 by the Werkzeug Team, see AUTHORS for more details.
    :license: BSD, see LICENSE for more details.
"""
import re
from werkzeug._compat import text_type, PY2, to_unicode, \
     to_native, implements_to_string, try_coerce_native, \
     normalize_string_tuple, make_literal_wrapper, \
     fix_tuple_repr
from werkzeug._internal import _encode_idna, _decode_idna
from werkzeug.datastructures import MultiDict, iter_multi_items
from collections import namedtuple


# A regular expression for what a valid schema looks like
_scheme_re = re.compile(r'^[a-zA-Z0-9+-.]+$')

# Characters that are safe in any part of an URL.
_always_safe = (b'abcdefghijklmnopqrstuvwxyz'
                b'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_.-+')

_hexdigits = '0123456789ABCDEFabcdef'
_hextobyte = dict(
    ((a + b).encode(), int(a + b, 16))
    for a in _hexdigits for b in _hexdigits
)


_URLTuple = fix_tuple_repr(namedtuple('_URLTuple',
    ['scheme', 'netloc', 'path', 'query', 'fragment']))


class _URLMixin(object):
    __slots__ = ()

    def replace(self, **kwargs):
        """Return an URL with the same values, except for those parameters
        given new values by whichever keyword arguments are specified."""
        return self._replace(**kwargs)

    @property
    def host(self):
        """The host part of the URL if available, otherwise `None`.  The
        host is either the hostname or the IP address mentioned in the
        URL.  It will not contain the port.
        """
        return self._split_host()[0]

    @property
    def ascii_host(self):
        """Works exactly like :attr:`host` but will return a result that
        is restricted to ASCII.  If it finds a netloc that is not ASCII
        it will attempt to idna decode it.  This is useful for socket
        operations when the URL might include internationalized characters.
        """
        rv = self.host
        if rv is not None and isinstance(rv, text_type):
            rv = _encode_idna(rv)
        return to_native(rv, 'ascii', 'ignore')

    @property
    def port(self):
        """The port in the URL as an integer if it was present, `None`
        otherwise.  This does not fill in default ports.
        """
        try:
            rv = int(to_native(self._split_host()[1]))
            if 0 <= rv <= 65535:
                return rv
        except (ValueError, TypeError):
            pass

    @property
    def auth(self):
        """The authentication part in the URL if available, `None`
        otherwise.
        """
        return self._split_netloc()[0]

    @property
    def username(self):
        """The username if it was part of the URL, `None` otherwise.
        This undergoes URL decoding and will always be a unicode string.
        """
        rv = self._split_auth()[0]
        if rv is not None:
            return _url_unquote_legacy(rv)

    @property
    def raw_username(self):
        """The username if it was part of the URL, `None` otherwise.
        Unlike :attr:`username` this one is not being decoded.
        """
        return self._split_auth()[0]

    @property
    def password(self):
        """The password if it was part of the URL, `None` otherwise.
        This undergoes URL decoding and will always be a unicode string.
        """
        rv = self._split_auth()[1]
        if rv is not None:
            return _url_unquote_legacy(rv)

    @property
    def raw_password(self):
        """The password if it was part of the URL, `None` otherwise.
        Unlike :attr:`password` this one is not being decoded.
        """
        return self._split_auth()[1]

    def decode_query(self, *args, **kwargs):
        """Decodes the query part of the URL.  Ths is a shortcut for
        calling :func:`url_decode` on the query argument.  The arguments and
        keyword arguments are forwarded to :func:`url_decode` unchanged.
        """
        return url_decode(self.query, *args, **kwargs)

    def join(self, *args, **kwargs):
        """Joins this URL with another one.  This is just a convenience
        function for calling into :meth:`url_join` and then parsing the
        return value again.
        """
        return url_parse(url_join(self, *args, **kwargs))

    def to_url(self):
        """Returns a URL string or bytes depending on the type of the
        information stored.  This is just a convenience function
        for calling :meth:`url_unparse` for this URL.
        """
        return url_unparse(self)

    def decode_netloc(self):
        """Decodes the netloc part into a string."""
        rv = _decode_idna(self.host or '')

        if ':' in rv:
            rv = '[%s]' % rv
        port = self.port
        if port is not None:
            rv = '%s:%d' % (rv, port)
        auth = ':'.join(filter(None, [
            _url_unquote_legacy(self.raw_username or '', '/:%@'),
            _url_unquote_legacy(self.raw_password or '', '/:%@'),
        ]))
        if auth:
            rv = '%s@%s' % (auth, rv)
        return rv

    def to_uri_tuple(self):
        """Returns a :class:`BytesURL` tuple that holds a URI.  This will
        encode all the information in the URL properly to ASCII using the
        rules a web browser would follow.

        It's usually more interesting to directly call :meth:`iri_to_uri` which
        will return a string.
        """
        return url_parse(iri_to_uri(self).encode('ascii'))

    def to_iri_tuple(self):
        """Returns a :class:`URL` tuple that holds a IRI.  This will try
        to decode as much information as possible in the URL without
        losing information similar to how a web browser does it for the
        URL bar.

        It's usually more interesting to directly call :meth:`uri_to_iri` which
        will return a string.
        """
        return url_parse(uri_to_iri(self))

    def _split_netloc(self):
        if self._at in self.netloc:
            return self.netloc.split(self._at, 1)
        return None, self.netloc

    def _split_auth(self):
        auth = self._split_netloc()[0]
        if not auth:
            return None, None
        if self._colon not in auth:
            return auth, None
        return auth.split(self._colon, 1)

    def _split_host(self):
        rv = self._split_netloc()[1]
        if not rv:
            return None, None

        if not rv.startswith(self._lbracket):
            if self._colon in rv:
                return rv.split(self._colon, 1)
            return rv, None

        idx = rv.find(self._rbracket)
        if idx < 0:
            return rv, None

        host = rv[1:idx]
        rest = rv[idx + 1:]
        if rest.startswith(self._colon):
            return host, rest[1:]
        return host, None


@implements_to_string
class URL(_URLTuple, _URLMixin):
    """Represents a parsed URL.  This behaves like a regular tuple but
    also has some extra attributes that give further insight into the
    URL.
    """
    __slots__ = ()
    _at = '@'
    _colon = ':'
    _lbracket = '['
    _rbracket = ']'

    def __str__(self):
        return self.to_url()

    def encode_netloc(self):
        """Encodes the netloc part to an ASCII safe URL as bytes."""
        rv = self.ascii_host or ''
        if ':' in rv:
            rv = '[%s]' % rv
        port = self.port
        if port is not None:
            rv = '%s:%d' % (rv, port)
        auth = ':'.join(filter(None, [
            url_quote(self.raw_username or '', 'utf-8', 'strict', '/:%'),
            url_quote(self.raw_password or '', 'utf-8', 'strict', '/:%'),
        ]))
        if auth:
            rv = '%s@%s' % (auth, rv)
        return rv.encode('ascii')

    def encode(self, charset='utf-8', errors='replace'):
        """Encodes the URL to a tuple made out of bytes.  The charset is
        only being used for the path, query and fragment.
        """
        return BytesURL(
            self.scheme.encode('ascii'),
            self.encode_netloc(),
            self.path.encode(charset, errors),
            self.query.encode(charset, errors),
            self.fragment.encode(charset, errors)
        )


class BytesURL(_URLTuple, _URLMixin):
    """Represents a parsed URL in bytes."""
    __slots__ = ()
    _at = b'@'
    _colon = b':'
    _lbracket = b'['
    _rbracket = b']'

    def __str__(self):
        return self.to_url().decode('utf-8', 'replace')

    def encode_netloc(self):
        """Returns the netloc unchanged as bytes."""
        return self.netloc

    def decode(self, charset='utf-8', errors='replace'):
        """Decodes the URL to a tuple made out of strings.  The charset is
        only being used for the path, query and fragment.
        """
        return URL(
            self.scheme.decode('ascii'),
            self.decode_netloc(),
            self.path.decode(charset, errors),
            self.query.decode(charset, errors),
            self.fragment.decode(charset, errors)
        )


def _unquote_to_bytes(string, unsafe=''):
    if isinstance(string, text_type):
        string = string.encode('utf-8')
    if isinstance(unsafe, text_type):
        unsafe = unsafe.encode('utf-8')
    unsafe = frozenset(bytearray(unsafe))
    bits = iter(string.split(b'%'))
    result = bytearray(next(bits, b''))
    for item in bits:
        try:
            char = _hextobyte[item[:2]]
            if char in unsafe:
                raise KeyError()
            result.append(char)
            result.extend(item[2:])
        except KeyError:
            result.extend(b'%')
            result.extend(item)
    return bytes(result)


def _url_encode_impl(obj, charset, encode_keys, sort, key):
    iterable = iter_multi_items(obj)
    if sort:
        iterable = sorted(iterable, key=key)
    for key, value in iterable:
        if value is None:
            continue
        if not isinstance(key, bytes):

apps/news/views.py
# -*- coding: utf-8 -*-
from urlparse import urljoin
from google.appengine.api import memcache
from lxml import etree
from apps.utils.paginator import Paginator, EmptyPage, InvalidPage
from flask import Blueprint, render_template
from apps.news.models import Post, Tag
import flask
import config
from flask import abort
import site_map
import itertools
import util
from werkzeug.contrib.atom import AtomFeed

mod = Blueprint(
    'news',
    __name__,
    template_folder='templates',
    url_prefix='/blog'
)

def get_paginator(posts, page, posts_per_page=20):
    paginator = Paginator(posts, posts_per_page)
    try:
        posts = paginator.page(page)
    except (EmptyPage, InvalidPage):
        posts = paginator.page(paginator.num_pages)
    return posts


main_section_item = site_map.MAP[1]


TAG_RANK = ("tagRank10", "tagRank9",
            "tagRank8", "tagRank7", "tagRank6",
            "tagRank5", "tagRank4", "tagRank3",
            "tagRank2", "tagRank1")


def create_posts_query():
    """
    Creates new public posts query object with created sorting desc
    :return: new query instance
    """
    return Post.query(Post.is_public == True).order(-Post.created)


def compute_rank(tag_title, count, totalcount):
    """Compute taglevel from frequency of tag"""
    index = int(float(count) / float(totalcount) * 10)
    return Tag(tag_title, TAG_RANK[index])


def create_tag_rank(articles):
    """Create tag rank"""
    tag_count_dict = {}
    total_count = 0
    for article in articles:
        for t in article.tags:
            total_count += 1
            if t in tag_count_dict:
                tag_count_dict[t] += 1
            else:
                tag_count_dict[t] = 1
    tags = []
    append = lambda tag_title: tags.append(compute_rank(tag_title, tag_count_dict[tag_title], total_count))
    map(append, tag_count_dict)
    return sorted(tags, key=lambda tag: tag.title)


class FileResolver(etree.Resolver):
    def resolve(self, url, identifier, context):
        return self.resolve_filename(url, context)


MONTHS = {
    1: u"Январь",
    2: u"Февраль",
    3: u"Март",
    4: u"Апрель",
    5: u"Май",
    6: u"Июнь",
    7: u"Июль",
    8: u"Август",
    9: u"Сентябрь",
    10: u"Октябрь",
    11: u"Ноябрь",
    12: u"Декабрь"
}


def month_tuple_to_string(month):
    return u'{0} ({1})'.format(MONTHS[month[0]], month[1])

mod.add_app_template_filter(month_tuple_to_string, 'month_tuple_to_string')


@mod.route('/', defaults={'page': 1})
@mod.route('/page/<int:page>/')
def index(page):
    posts = create_posts_query()
    title = main_section_item[site_map.TITLE]
    tag = util.param('tag')
    if tag:
        title = u"Все посты по метке: {0}".format(tag)
        posts = posts.filter(Post.tags.IN([tag]))

    if page > 1:
        if not tag:
            title = u" {0}-я страница".format(page)
        else:
            title = u" {0}-я страница постов по метке: {1}".format(page, tag)

    all_posts = util.run_query(create_posts_query())

    archieve = {}
    for ym, group in itertools.groupby(all_posts, key=lambda post: (post.created.year, post.created.month)):
        if ym[0] not in archieve:
            archieve[ym[0]] = []
        for m, months in itertools.groupby(group, key=lambda p: p.created.month):
            posts_count = len(filter(None, months))
            k = (m, posts_count)
            archieve[ym[0]].append(k)

    posts = get_paginator(util.run_query(posts), page)

    return render_template(
        'news/index.html',
        title=title,
        posts=posts,
        archieve=archieve,
        tag_selected=tag,
        tags=create_tag_rank(all_posts),
        key=main_section_item[site_map.ID],
    )


@mod.route('/recent.atom')
def recent_feed():
    feed = AtomFeed('{0} feed'.format(config.CONFIG_DB.brand_name),
                    feed_url=flask.request.url, url=flask.request.url_root)
    limit = config.ATOM_FEED_LIMIT
    if util.param('limit'):
        limit = util.param('limit', int)

    articles = util.run_query(create_posts_query(), limit)

    make_external = lambda url: urljoin(flask.request.url_root, url)

    for article in articles:
        feed.add(article.title, unicode(article.short_text),
                 content_type='html',
                 author="Alexander Egorov",
                 url=make_external(flask.url_for('news.post', key_id=article.key.id())),
                 updated=article.modified,
                 published=article.created)
    return feed.get_response()


@mod.route('/<int:key_id>/', endpoint='post')
@mod.route('/<int:key_id>.html', endpoint='post')
def get_post(key_id):
    post = Post.retrieve_by_id(key_id)
    if not post or not post.is_public:
        abort(404)

    content = post.text
    if content and content.startswith('<?xml version="1.0"?>'):
        parser = etree.XMLParser(load_dtd=False, dtd_validation=False)
        parser.resolvers.add(FileResolver())

        xml_input = etree.fromstring(post.text, )
        xslt_root = etree.parse('apache/apache_manualpage.xsl', parser)
        transform = etree.XSLT(xslt_root)

        content = unicode(transform(xml_input))

    original_limit = 5
    limit = original_limit
    offset = 0
    while True:
        posts = get_posts_ids(limit, offset)
        if key_id in posts: break
        offset += limit

    if offset > 0:
        limit += offset
    offset += original_limit

    last = util.run_query(create_posts_query(), limit)
    return render_template(
        'news/post.html',
        title=post.title,
        main_post=post,
        content=content,
        last=last,
        limit=original_limit,
        offset=offset,
        full_uri=urljoin(flask.request.url_root, flask.url_for('news.post', key_id=key_id)),
    )


def create_posts_keys(limit, offset):
    return 'posts_id_desc_limit_{0}_offset_{1}'.format(limit, offset)


def get_posts_ids(limit, offset):
    key = create_posts_keys(limit, offset)
    latest = memcache.get(key)
    if latest is None:
        keys = util.run_query(create_posts_query(), limit, offset=offset, keys_only=True)
        latest = ','.join([str(k.id()) for k in keys])
        memcache.add(key, latest, 86400)
    return [long(k) for k in latest.split(',')]

templates/admin.html
<!DOCTYPE html>
<html class="{{html_class}}" lang="en" data-channel-name="{{channel_name}}">
  <head>
    <meta charset="utf-8">
    <title>
      {% block title %}
        {% if title %}
          {{title}} |
        {% endif %}
      {% endblock %}
      {{config.BRAND_NAME}}
    </title>

    {% include 'bit/style.html' %}
    {% block head %}{% endblock %}
  </head>

  <body>
    {% include 'admin/top_bar.html' %}

    <div class="container">
      {% include 'bit/notifications.html' %}
      {% block content %}{% endblock %}
    </div>


    {% include 'bit/script.html' %}
    {% block scripts %}{% endblock %}
  </body>
</html>

templates/base.html
<!DOCTYPE html>
{% autoescape true %}
{% strip %}
<html class="{% block html_class %}{{html_class}}{% endblock %}" lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
      # block title
        # if title
          {{title}}&nbsp;|&nbsp;
        # endif
      # endblock
      {{config.CONFIG_DB.brand_name}}
    </title>
    <link href="{{ url_for('news.recent_feed') }}"
      rel="alternate"
      title="Recent Posts"
      type="application/atom+xml">
    # include 'bit/style.html'
    # block head
    # endblock
    # block searchscript
    # endblock
    # include 'bit/analytics.html'
  </head>

  <body>
<!--noindex-->
    # include 'bit/top_bar.html'
    # include 'bit/breadcrumbs.html'
<!--/noindex-->
    <div class="container-fluid main-container">
      # include 'bit/notifications.html'
      # block content
      # endblock
    </div>
<!--noindex-->
    # include 'bit/footer.html'
    # include 'bit/script.html'
    # if not current_user.admin and config.CONFIG_DB.analytics_id
        <script type="text/javascript">
          jQuery.error = function (message) {
              _gaq.push(['_trackEvent', 'jQuery Error', message, navigator.userAgent]);
          }
        </script>
    # endif
    # block scripts
    # endblock
<!--/noindex-->
  </body>
</html>
{% endstrip %}
{% endautoescape %}

templates/error.html
# extends 'base.html'

# block content
  <div class="jumbotron">
    <h2>
      <small>{{error.code}}</small>
      Oh no...! {{error.name}}
    </h2>
    <p class="lead">
      Maybe it's our fault.. maybe it's yours.. but either case, this page is unavailable!
    </p>
  </div>

  <hr>

  <div class="row">
    <div class="span12">
      <img
          src="http://i.imgur.com/wzBcYCV.png"
          class="img-error"
          alt="xkcd: Wisdom of the Ancients"
          title="xkcd: Wisdom of the Ancients"
        >
    </div>
  </div>
# endblock

templates/feedback.html
# extends 'base.html'

# block content
  <div class="page-header">
    <h1>
      {{title}}
      <small>Есть вопросы и предложения? Всегда пожалуйста :)</small>
    </h1>
  </div>
  <div class="row">
    <div class="span4">
      <form class="form" method="POST" action=".">
        <fieldset>
          {{form.csrf_token}}

          # set form_field = form.subject
          # include 'bit/form_text_field.html'

          # set form_field = form.message
          # include 'bit/form_textarea_field.html'

          # set form_field = form.email
          # include 'bit/form_text_field.html'

          <button type="submit" class="btn btn-primary btn-block btn-loading" data-loading-text="Sending Feedback..">
            Оправить
          </button>
        </fieldset>
      </form>
    </div>
  </div>
# endblock

templates/profile.html
# extends 'base.html'

# block content
  <div class="page-header">
    <h1>{{user_db.name}}</h1>
  </div>
  <div class="row">
    <div class="span2">
      <a class="thumbnail" href="http://gravatar.com" target="_blank">
        <img src="{{user_db.avatar_url}}&amp;s=170" alt="Gravatar photo of {{user_db.name}}">
      </a>
    </div>
    <div class="span4">
      <form class="form" method="POST" action=".">
        <fieldset>
          {{form.csrf_token}}

          <div class="control-group ">
            <label class="control-label" for="username">Имя пользователя</label>
            <div class="controls">
              <input class="span4" id="username" name="username" type="text" value="{{user_db.username}}" readonly="readonly">
            </div>
          </div>

          # set form_field = form.name
          # include 'bit/form_text_field.html'

          # set form_field = form.email
          # include 'bit/form_text_field.html'

          <button type="submit" class="btn btn-primary btn-block btn-loading" data-loading-text="Обновление профиля...">
            Обновить профиль
          </button>
        </fieldset>
      </form>
    </div>
  </div>
# endblock

templates/search.html
# extends 'base.html'

# block searchscript
# include 'bit/searchscript.html'
# endblock

# block content
  <div class="row">
    <div class="span12">
        <div class="gcse-search" data-resultsUrl="/search/" data-queryParameterName="q">
        </div>
    </div>
  </div>
# endblock

templates/signin.html
# extends 'base.html'

# block content
  <div class="page-header">
    <h1>
      {{title}}
      <small>
        Займет только 8 секунд!
      </small>
    </h1>
  </div>
  <div class="row">
    <div class="span4 offset4">
      <a class="btn btn-block btn-large btn-google" href="{{google_signin_url}}">
        <i class="icon icon-google-plus"></i>
        Войти с учетной записью Google
      </a>

      # if config.CONFIG_DB.facebook_app_id and config.CONFIG_DB.facebook_app_secret
        <a class="btn btn-block btn-large btn-facebook" href="{{facebook_signin_url}}">
          <i class="icon icon-facebook"></i>
          Войти с учетной записью Facebook
        </a>
      # endif

      # if config.CONFIG_DB.twitter_consumer_key and config.CONFIG_DB.twitter_consumer_secret
        <a class="btn btn-block btn-large btn-twitter" href="{{twitter_signin_url}}">
          <i class="icon icon-twitter"></i>
          Войти с учетной записью Twitter
        </a>
      # endif
    </div>
  </div>
# endblock

templates/sitemap.html
<?xml version="1.0" encoding="UTF-8"?>
{% strip %}
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    {% for page in pages %}
    <url>
        <loc>{{ page["loc"] | safe }}</loc>
        <changefreq>{{ page["changefreq"] }}</changefreq>
        <priority>{{ page["priority"] }}</priority>
    </url>
    {% endfor %}
</urlset>
{% endstrip %}

templates/user_list.html
# extends 'base.html'

# block content
  <div class="page-header">
    <h1>
      {{title}}
    </h1>
  </div>

  <div class="row-fluid">
    <div class="span12">
      <div class="well well-small">
        <div class="btn-group">
          <a class="btn btn-small dropdown-toggle btn-success" data-toggle="dropdown" href="#">
            Limit - {{request.args.get('limit') or 'Default'}}
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><a href="{{url_for('user_list')}}">{{config.DEFAULT_DB_LIMIT}} (Default)</a></li>
            <li class="divider"></li>
            <li><a href="{{url_for('user_list', limit=2)}}">2</a></li>
            <li><a href="{{url_for('user_list', limit=4)}}">4</a></li>
            <li><a href="{{url_for('user_list', limit=8)}}">8</a></li>
            <li><a href="{{url_for('user_list', limit=16)}}">16</a></li>
          </ul>
        </div>
        <div class="btn-group">
          <a class="btn btn-small dropdown-toggle btn-danger" data-toggle="dropdown" href="#">
            Admins - {{request.args.get('admin') or 'None'}}
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><a href="{{url_for('user_list')}}">None</a></li>
            <li class="divider"></li>
            <li><a href="{{url_for('user_list', admin='true')}}">Show Admins</a></li>
            <li><a href="{{url_for('user_list', admin='false')}}">Hide Admins</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="row-fluid">
    <div class="span12">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th class="span1">ID</th>
            <th class="span1">Photo</th>
            <th class="span3">
              # if request.args.get('order') == 'name'
                <a href="{{url_for('user_list', order='-name')}}">Name <i class="icon-chevron-up"></i></a>
              # elif request.args.get('order') == '-name'
                <a href="{{url_for('user_list', order='name')}}">Name <i class="icon-chevron-down"></i></a>
              #else
                <a href="{{url_for('user_list', order='name')}}">Name</a>
              #endif
            </th>
            <th class="span3">
              # if request.args.get('order') == 'email'
                <a href="{{url_for('user_list', order='-email')}}">Email <i class="icon-chevron-up"></i></a>
              # elif request.args.get('order') == '-email'
                <a href="{{url_for('user_list', order='email')}}">Email <i class="icon-chevron-down"></i></a>
              #else
                <a href="{{url_for('user_list', order='email')}}">Email</a>
              #endif
            </th>
            <th class="span2">
              # if request.args.get('order') == 'created'
                <a href="{{url_for('user_list', order='-created')}}">Created <i class="icon-chevron-up"></i></a>
              # elif request.args.get('order') == '-created'
                <a href="{{url_for('user_list', order='created')}}">Created <i class="icon-chevron-down"></i></a>
              #else
                <a href="{{url_for('user_list', order='created')}}">Created</a>
              #endif
            </th>
            <th class="span2">
              # if request.args.get('order') == 'modified'
                <a href="{{url_for('user_list', order='-modified')}}">Modified <i class="icon-chevron-up"></i></a>
              # elif request.args.get('order') == '-modified'
                <a href="{{url_for('user_list', order='modified')}}">Modified <i class="icon-chevron-down"></i></a>
              #else
                <a href="{{url_for('user_list', order='modified')}}">Modified</a>
              #endif
            </th>
          </tr>
        </thead>
        <tbody>
          # for user_db in user_dbs
            <tr>
              <td>{{user_db.key.id()}}</td>
              <td>
                <img src="{{user_db.avatar_url}}&amp;s=24" alt="Gravatar for {{user_db.name}}">
              </td>
              <td>
                {{user_db.name}}
                # if user_db.admin
                  <i class="icon-cog" title="Administrator"></i>
                # endif
              </td>
              <td>{{user_db.email}}</td>
              <td>
                <abbr title="{{user_db.created_utc}}">
                  {{user_db.created_ago}}
                </abbr>
              </td>
              <td>
                <abbr title="{{user_db.modified_utc}}">
                  {{user_db.modified_ago}}
                </abbr>
              </td>
            </tr>
          # endfor
        </tbody>
      </table>
    </div>
  </div>
  # if more_url
    <div class="row-fluid">
      <div class="span12">
        <ul class="pager">
          <li>
            <a href="{{more_url}}">Next Page</a>
          </li>
        </ul>
      </div>
    </div>
  # endif
# endblock

templates/welcome.html
# extends 'base.html'


# block head
    <meta name="google-site-verification" content="PHs3gMRw0_sIAdVqjk38_fbq9h3VGHkkIq3w1chJXWs"/>
# endblock

# block searchscript
# include 'bit/searchscript.html'
# endblock

# block content
{% strip %}
# include 'bit/search.html'

<div class="row-fluid">
    <div class="span6">
        <h2><a href="{{ url_for('news.index') }}">Блог</a></h2>
        {% if posts %}
            <dl id="log">
                {% for post in posts %}
                    {% include 'news/post_box.html' %}
                {% endfor %}
            </dl>
        {% else %}
            <p>Пока ничего нового.</p>
        {% endif %}
    </div>
    <div class="span6">
        <h2>Про апачей</h2>
        {% include 'portfolio/apache_documents_list.html' %}
    </div>
</div>
{% endstrip %}
# endblock